### ISSUE TITLE
80 - Detail page missing Configurators

### ISSUE THREAD

**Issue by GordonPeg** [Allsteel/hni-textiles-webcomponents#184] opened 2015-10-23 15:35 UTC
#80
Chrome 

Some detail pages appears to be missing the configurator.  The hero images and smaller swatch image look good but when I was checking the configurator, it was missing on several patterns

-Selected Appoint Seating - Lawn (Seating Grade 2)
-Hero image look correct (not sure of the resolution)
-Checked for the configurator and it was not on the page
-Repeated several times and received mixed results - 
      Perennial is correct, 
      Chatterbox is missing configurator

[Textile testing_Test 79.pdf](https://github.com/Allsteel/hni-textiles-webcomponents/files/19528/Textile.testing_Test.79.pdf)

**Comment by mbr4nt** [comment] 2015-10-23 15:36
Duplicate #79

**Comment by mbr4nt** [comment] 2015-10-23 15:45
That is due to not having repeatable swatches for every fabric. @mcinnisb , close?

**Comment by mbr4nt** [comment] 2015-10-23 15:53
Also, there are no configurators for panels. We only have chairs.

**Comment by mcinnisb** [comment] 2015-10-27 12:45
Confirmed closing the issue.

**Closed by mcinnisb** 2015-10-27 12:45 UTC
Labels: bug
