### ISSUE TITLE
Textiles Search Page - Duplicate Pattern Names

### ISSUE THREAD

**Issue by WilliamsHeidi** [Allsteel/hni-textiles-webcomponents#107] opened 2015-10-16 13:25 UTC
It appears some of the Pattern names are duplicated.  I have looked through someone these and the supplier names are the same.  I am not seeing anything that would say there needs to be two.

Here are a few names:
Promessa
Spun
Brisa
I-Beam

**Comment by mcinnisb** [comment] 2015-10-16 13:27
Not sure if this is a data or functionality issue. Assigning to Mateus first. Mateus, if it's strictly data assign to Brandon Garrett.

**Comment by mbr4nt** [comment] 2015-10-16 14:51
A lot of those HBF fabrics have that problem. We changed the order code at some point and some seem to have been left behind, which causes the system to see them as two different fabrics. It needs to be fixed in the data.

**Comment by garrettbt** [comment] 2015-10-16 15:03
The difference is the program type or the code itself. For example I-Beam while the textile name is the same, there are 2 separate textile fabric codes, 1 for the Partnership textiles and 1 for the Graded-In textiles. These are actually structured separately in GFR. If something has changed around these, I will be happy to make the needed changes, but as far as I know they need to be separate.

**Comment by mbr4nt** [comment] 2015-10-19 20:21
It sounds like those patterns are duplicate by design. Closing the issue.

**Closed by mbr4nt** 2015-10-19 20:21 UTC
