### ISSUE TITLE
49 - Fabric Grade Filter -  Display treatment does not match other filters

### ISSUE THREAD

**Issue by GordonPeg** [Allsteel/hni-textiles-webcomponents#161] opened 2015-10-23 13:58 UTC
#49 

1 -Selected Application - Seating
2 -Selected Pricing Grade and noticed the display was different from the other search results:
    -Text color different
    -Pricing grade has a line separating each result/grade, others do not have a line

Chrome 

[Textile testing_Test 49.pdf](https://github.com/Allsteel/hni-textiles-webcomponents/files/19431/Textile.testing_Test.49.pdf)

**Comment by GordonPeg** [comment] 2015-10-23 14:15
Applied label

**Comment by mbr4nt** [comment] 2015-10-23 15:50
By design, as requested by @mcinnisb . Closing.

**Closed by mbr4nt** 2015-10-23 15:50 UTC
Labels: bug
