### ISSUE TITLE
Mindshare- bench, screen, bolster

### ISSUE THREAD

**Issue by tjebkesk** [Allsteel/hni-textiles-webcomponents#297] opened 2015-12-21 17:19 UTC
All fabric for Mindshare is upholstered as Railroad, all tile images are pattern cut which is not correct.  Need to rotate the fabrics all 90 degrees.

**Comment by mbr4nt** [comment] 2015-12-23 15:18
Heidi, please coordinate. 

Thank you.

**Comment by WilliamsHeidi** [comment] 2015-12-28 18:35
This is not a bug.  This needs to be fixed in the configurator but was originally approved.  Closing as it is not a bug.

**Closed by WilliamsHeidi** 2015-12-28 18:35 UTC
Labels: bug
