### ISSUE TITLE
Filter Functionality on Page Refresh

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#146] opened 2015-10-21 20:05 UTC
When using the browser's refresh button on the search page after applying a filter, the entire list of fabrics reloads. This makes sense. However, the LeftNav still lists the fabric filters as being applied. This should really show a blank slate. This is true in Chrome and IE11.

![image](https://cloud.githubusercontent.com/assets/14330996/10648627/2830d928-7805-11e5-84b5-571c57484f97.png)

![image](https://cloud.githubusercontent.com/assets/14330996/10648641/32b9e592-7805-11e5-94f9-5439a3230862.png)

**Comment by mbr4nt** [comment] 2015-10-21 20:17
@hamiltonk , the filter state goes to the url. That's by design, so people can share a link with filters applied. like this: here's a link to HBF textiles: http://qa.allsteeloffice.com/design-resources/textiles-and-finishes/fabrics/?k=&supplier=HBF+Textiles 

I'm closing this.

**Comment by hamiltonk** [comment] 2015-10-21 20:22
Re-opening this. If we want to have the refresh go to the page with filters applied, that's fine. But the filters are listed in the LeftNav and NOT applied. We just need it to be consistent.

**Comment by mbr4nt** [comment] 2015-10-21 20:25
Got it. I'll see what is going on.

**Comment by hamiltonk** [comment] 2015-10-22 18:34
Notified Kristi of fix via email.

**Comment by mbr4nt** [comment] 2015-10-22 21:11
@hamiltonk  don't reopen it though. It needs to remain closed, unless re-tested and failed.

**Closed by mbr4nt** 2015-10-22 21:11 UTC
Labels: bug

**Comment by hamiltonk** [comment] 2015-10-23 15:57
Kristi S verified that this is resolved.
