### ISSUE TITLE
Search in IE11

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#111] opened 2015-10-16 20:25 UTC
When trying to search in IE11, I don't see the same toolbar that I see in Chrome. There is a search, but it is all the way at the right. This appears to be the site search bar, though, and not the textiles search field.

![ie11](https://cloud.githubusercontent.com/assets/14330996/10552527/16548342-741a-11e5-9e4c-d0be917018ab.png)

**Comment by felipebbtoledo** [comment] 2015-10-16 21:13
@mcinnisb This is not the latest version of the header. The search field has been changed to reproduce prod's look and feel.

**Comment by mbr4nt** [comment] 2015-10-19 20:18
@felipebbtoledo something seems to be missing, the bar came all white.

![image](https://cloud.githubusercontent.com/assets/12057269/10590116/8ebbfe12-7674-11e5-8a75-3f8beaa3134b.png)

**Comment by felipebbtoledo** [comment] 2015-10-19 22:25
This has been fixed now and published to qa now.

**Closed by felipebbtoledo** 2015-10-19 22:25 UTC
