### ISSUE TITLE
Missing product from Configurator

### ISSUE THREAD

**Issue by tjebkesk** [Allsteel/hni-textiles-webcomponents#293] opened 2015-12-21 17:08 UTC
The following products need to be added to configurator-

Hedge
Access Upholstery Work 
Access Upholstery Stool

**Comment by tucaz** [comment] 2015-12-23 15:48
@mbr4nt We don't have Hedge as new configurator and Access chairs are there. Should I close this?

**Comment by mbr4nt** [comment] 2015-12-23 16:55
@heidi will get a quote from farm for Hedge and others.

**Comment by WilliamsHeidi** [comment] 2015-12-28 18:34
Hedge is not a bug.  I am closing since all other seats are available.

**Closed by WilliamsHeidi** 2015-12-28 18:34 UTC
Labels: bug, ready to ReTest

**Comment by SorensenK** [comment] 2015-12-29 14:44
checked 10 fabrics
