### ISSUE TITLE
Textiles Detail Page - Attribute Order

### ISSUE THREAD

**Issue by WilliamsHeidi** [Allsteel/hni-textiles-webcomponents#118] opened 2015-10-20 16:42 UTC
The attributes are not in the correct order. Here is the correct order.
![image](https://cloud.githubusercontent.com/assets/13138473/10614387/a8553766-771f-11e5-992e-f2c82588d3a9.png)

**Comment by tucaz** [comment] 2015-10-20 22:14
@mbr4nt the order of the properties are correct. However, Grade and Order Code were still not removed from the "hard coded" list. Also, color name is on the page title and that's why it's not on the list.

So the problem is not the order, but a matter of removing the existing hard coded properties.

**Comment by mbr4nt** [comment] 2015-10-21 13:37
@WilliamsHeidi , just to confirm, won't we have pricing grade?

**Comment by WilliamsHeidi** [comment] 2015-10-21 20:30
Grade is set at the Pattern level.  It is part of the search page.

**Comment by tucaz** [comment] 2015-10-22 21:28
Fixed in QA

**Closed by tucaz** 2015-10-22 21:28 UTC
