### ISSUE TITLE
AO - Textile landing page, 3 of the 4 inspiration primary images are missing  (ship is the only one)

### ISSUE THREAD

**Issue by GordonPeg** [Allsteel/hni-textiles-webcomponents#324] opened 2016-01-09 02:55 UTC
AO - Textile landing page, 3 of the 4 inspiration primary images are missing  (the tall ship is the only one).  As you rotate thru the other areas, the primary image does not display

http://www.allsteeloffice.com/design-resources/textiles-and-finishes

**Comment by WilliamsHeidi** [comment] 2016-01-09 02:59
duplicate of #313

**Closed by WilliamsHeidi** 2016-01-09 02:59 UTC
Labels: go-live bug
