### ISSUE TITLE
Missing Configurator - Textiles Detail Page - Equation

### ISSUE THREAD

**Issue by GordonPeg** [Allsteel/hni-textiles-webcomponents#267] opened 2015-12-21 16:09 UTC
Missing Configurator - Textiles Detail Page - Equation:

**Comment by tucaz** [comment] 2015-12-23 20:53
Duplicate of #282

**Comment by WilliamsHeidi** [comment] 2015-12-28 17:56
I was told that we had repeatables for everything but two HBF fabrics.  Can you please double-check there isn't one for this fabric?

**Comment by GordonPeg** [comment] 2016-01-06 16:26
Reviewed and passed

**Closed** 2016-01-07 22:01 UTC
Labels: no repeatable, passed
